# 2024-05: Default bind will be changed to localhost soon -> use 0.0.0.0
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheusremotewrite/mimir:
    endpoint: http://mimir:9009/api/v1/push
    tls:
      insecure: true
    headers:
      "X-Scope-OrgID": local
  otlp:
    endpoint: http://tempo:4317
    compression: none # Compression is not needed for internal network communication
    tls:
      insecure: true
    headers:
      "X-Scope-OrgID": local
  otlphttp:
    endpoint: http://loki-write:3100/otlp
    compression: none # Compression is not needed for internal network communication
    tls:
      insecure: true
    headers:
      "X-Scope-OrgID": local

service:
  # https://opentelemetry.io/docs/collector/internal-telemetry/
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '[::0]'
                port: 8888
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite/mimir]
    traces:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlphttp]
